version: '3.8'

services:
  db:
    image: postgres:15
    container_name: parse-pg-db
    environment:
      POSTGRES_DB: parse
      POSTGRES_USER: parse
      POSTGRES_PASSWORD: Ylddwmswm123!
    ports:
      - "6432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
